### ISSUE TITLE
use modernizr instead of explicit @spec parameter

### ISSUE THREAD

**Issue by zowers** [ProLoser/Flexbox.less#11]
I have following modification benefiting from modernizr's rules, so no @spec argument is needed
```less
.flex(@flex-grow, @flex-shrink: 0, @flex-preferred: auto) {
    .flexboxlegacy & {
        -webkit-box-flex: @flex-grow;
        -moz-box-flex: @flex-grow;
        -ms-box-flex: @arguments;
        -o-box-flex: @arguments;
    }

    box-flex: @flex-grow;

    .no-flexbox & {
        width: @flex-preferred;
    }

    .flexbox & {
        -webkit-flex: @arguments;
        -moz-flex: @arguments;
        -ms-flex: @arguments;
        -o-flex: @arguments;
        flex: @arguments;
    }
}
```
so it can be used as:
```less
.flex(0, 0, 50px);
```
.flexbox and .flexboxlegacy detects are in modernizr@3-beta http://v3.modernizr.com/download/
modernizr@2 has issues (https://github.com/Modernizr/Modernizr/issues/812)
